# The slug is the name of the file w/o extension
name: Tag
plural_name: Tags
terms:
  -
    name: Tag 1
    slug: tag-1
  -
    name: Tag 2
    slug: tag-2
config:
    # /tags is 404 if false
    public_terms_route: false