# You can override configurations from default.yml here
# These configs will only take effect in the dev environment.
# Keep in mind that production (prod) is the default environment.
#
# If you want to change the environment on this machine to prod
# you have to rename .env.example to .env and set the APP_ENV to prod.
#
# Your production server and your dev server should have two
# different ".env" files. That is why the file is ignored by git.
#
# If you are not using a ".env" file or don't care what
# environment the app is in, then this does not apply to you.
#
# https://github.com/vlucas/phpdotenv
debug: true
http_cache.enabled: false