-
  name: categories
  singular_name: category
  mappings:
    -
      name: Web Development
      slug: web-development
    -
      name: Unix
      slug: unix
    -
      name: foo BAR baz
      slug: foo-bar-baz
-
  name: tags
  singular_name: tag
  mappings:
    -
      name: Tag 1
      slug: tag-1
    -
      name: Tag 2
      slug: tag-2